name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  video_player: ^2.2.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
    - assets/img_me_1.png
    - assets/img_me_2.png
    - assets/img_me_3.png
    - assets/img_me_4.png
    - assets/img_me_5.png
    - assets/project1.png
    - assets/icon-tistory.png
    - assets/icon-github.png
    - assets/mp4-climb2.mp4
    - assets/climb1.png
    - assets/project2.png
    - assets/project3.png